# Site settings
title: I3D Symposium
description: "ACM SIGGRAPH Symposium on Interactive 3D Graphics and Games" # I3D is an awesome conference!
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://i3dsymposium.org" # the base hostname & protocol for your site
lang: en-US
timezone: US/Pacific
email: general@i3dsymposium.org
github_username:  i3dsymposium

author:
  name: I3D Publicity Chair
  email: general@i3dsymposium.org

# Build settings
markdown: kramdown

plugins:
  - jekyll-redirect-from

exclude:
  - img_src

excerpt_separator: <!--more-->

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      layout: "default"

collections:
  - news

redirect_from:
  json: false
