# Site settings
title: I3D
email: general@i3dsymposium.org
description: "ACM SIGGRAPH Symposium on Interactive 3D Graphics and Games" # I3D is an awesome conference!
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://i3dsymposium.org" # the base hostname & protocol for your site
github_username:  i3dsymposium
## highlighter: pygments

# Build settings
markdown: kramdown

gems:
  - jekyll-redirect-from

exclude:
  - img_src

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      layout: "default"