# Site settings
title: I3D 2015
email: general@i3dsymposium.org
description: > # I3D is an awesome conference!
baseurl: "/2016/" # the subpath of your site, e.g. /blog/
url: "http://i3dsymposium.org" # the base hostname & protocol for your site
github_username:  i3dsymposium

# Build settings
markdown: kramdown
